// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEYW3pQ0Q_2QOBClisHcFPlwGx3MJQLuA',
    appId: '1:302010913465:web:94a437f1f825abd76c4168',
    messagingSenderId: '302010913465',
    projectId: 'project-sem-3-a97c8',
    authDomain: 'project-sem-3-a97c8.firebaseapp.com',
    storageBucket: 'project-sem-3-a97c8.appspot.com',
    measurementId: 'G-9X7J3YTS6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9BLRIbdp55FcYxN1qYq_8jY_lPVg58w',
    appId: '1:302010913465:android:b5ad7fa2277b5a906c4168',
    messagingSenderId: '302010913465',
    projectId: 'project-sem-3-a97c8',
    storageBucket: 'project-sem-3-a97c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzi_1N5hurdUnaNygwTDwtwO9l_euv9uU',
    appId: '1:302010913465:ios:084e14fb7bedd4bc6c4168',
    messagingSenderId: '302010913465',
    projectId: 'project-sem-3-a97c8',
    storageBucket: 'project-sem-3-a97c8.appspot.com',
    androidClientId: '302010913465-cn2aa1l958gtifb5lnif5br6a3653f3q.apps.googleusercontent.com',
    iosClientId: '302010913465-7t4lm0e36rbms3stckpjca4oj40lvmd9.apps.googleusercontent.com',
    iosBundleId: 'com.sleepholic.sleepholic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzi_1N5hurdUnaNygwTDwtwO9l_euv9uU',
    appId: '1:302010913465:ios:084e14fb7bedd4bc6c4168',
    messagingSenderId: '302010913465',
    projectId: 'project-sem-3-a97c8',
    storageBucket: 'project-sem-3-a97c8.appspot.com',
    androidClientId: '302010913465-cn2aa1l958gtifb5lnif5br6a3653f3q.apps.googleusercontent.com',
    iosClientId: '302010913465-7t4lm0e36rbms3stckpjca4oj40lvmd9.apps.googleusercontent.com',
    iosBundleId: 'com.sleepholic.sleepholic',
  );
}
